// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQYerEJdbolGZW8LL0fhpdgFyLVy7HUT4',
    appId: '1:704971532176:web:025423af78ec63618bb515',
    messagingSenderId: '704971532176',
    projectId: 'beshape-cd0d0',
    authDomain: 'beshape-cd0d0.firebaseapp.com',
    storageBucket: 'beshape-cd0d0.firebasestorage.app',
    measurementId: 'G-JYG4K4STW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7OGnwtJ4rYUyFJlAzXYLj6XSWLFSpJN4',
    appId: '1:704971532176:android:68d2673e67114d958bb515',
    messagingSenderId: '704971532176',
    projectId: 'beshape-cd0d0',
    storageBucket: 'beshape-cd0d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9cEJ44o5hdAtRYbtbbC69B6j6gDwTUzw',
    appId: '1:704971532176:ios:ec5a52c6f68dd37f8bb515',
    messagingSenderId: '704971532176',
    projectId: 'beshape-cd0d0',
    storageBucket: 'beshape-cd0d0.firebasestorage.app',
    iosBundleId: 'com.example.beShapeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9cEJ44o5hdAtRYbtbbC69B6j6gDwTUzw',
    appId: '1:704971532176:ios:ec5a52c6f68dd37f8bb515',
    messagingSenderId: '704971532176',
    projectId: 'beshape-cd0d0',
    storageBucket: 'beshape-cd0d0.firebasestorage.app',
    iosBundleId: 'com.example.beShapeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQYerEJdbolGZW8LL0fhpdgFyLVy7HUT4',
    appId: '1:704971532176:web:e830c3e7f47361818bb515',
    messagingSenderId: '704971532176',
    projectId: 'beshape-cd0d0',
    authDomain: 'beshape-cd0d0.firebaseapp.com',
    storageBucket: 'beshape-cd0d0.firebasestorage.app',
    measurementId: 'G-5FSJ2SNQ70',
  );
}
