// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// 
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAutEmbgb50MKyYpAU5KnWmsPFjA-ocj9U',
    appId: '1:744118623388:web:529da38000db8ec5df2159',
    messagingSenderId: '744118623388',
    projectId: 'beshape-9afaf',
    authDomain: 'beshape-9afaf.firebaseapp.com',
    storageBucket: 'beshape-9afaf.firebasestorage.app',
    measurementId: 'G-4JLX9NKV9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSpJRppHXUCjjSPdfuq_qwfUvFeZ9mJrM',
    appId: '1:744118623388:android:3956dcd457509f1ddf2159',
    messagingSenderId: '744118623388',
    projectId: 'beshape-9afaf',
    storageBucket: 'beshape-9afaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpf5IARSVNb3QhwYGhpbB2YtuCnjAzap0',
    appId: '1:744118623388:ios:a4e85446a0943e8cdf2159',
    messagingSenderId: '744118623388',
    projectId: 'beshape-9afaf',
    storageBucket: 'beshape-9afaf.firebasestorage.app',
    iosBundleId: 'com.example.beshape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpf5IARSVNb3QhwYGhpbB2YtuCnjAzap0',
    appId: '1:744118623388:ios:15ee8c2b53854383df2159',
    messagingSenderId: '744118623388',
    projectId: 'beshape-9afaf',
    storageBucket: 'beshape-9afaf.firebasestorage.app',
    iosBundleId: 'com.example.beShapeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAutEmbgb50MKyYpAU5KnWmsPFjA-ocj9U',
    appId: '1:744118623388:web:47f77a5ac7c49807df2159',
    messagingSenderId: '744118623388',
    projectId: 'beshape-9afaf',
    authDomain: 'beshape-9afaf.firebaseapp.com',
    storageBucket: 'beshape-9afaf.firebasestorage.app',
    measurementId: 'G-9M625JEWKR',
  );
}
